from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scenario_agent import (
    ASSET_CATALOG,
    MAX_SURVIVOR_RUBBLE_DISTANCE_METERS,
    MIN_ASSETS_BY_DIFFICULTY,
    MIN_HAZARDS_BY_DIFFICULTY,
    HazardZone,
    PlacedAsset,
    SCENARIO_BASE_AGENT,
    SCENARIO_MODEL,
    ScenarioAgent,
    SceneSpec,
    SurvivorLocation,
    SurvivorProfile,
    extract_json_object,
    nearest_rubble_distance,
    repair_scene,
)


class FakeManagedAgent:
    def __init__(self, response: str) -> None:
        self.response = response
        self.last_prompt: str | None = None

    def run_text(self, prompt: str) -> str:
        self.last_prompt = prompt
        return self.response

    def create(self) -> dict[str, bool]:
        return {"created": True}


def make_scene_json() -> str:
    return json.dumps(
        {
            "description": "earthquake collapse",
            "difficulty": "hard",
            "bounds": [20.0, 20.0, 3.0],
            "robot_start": [1.5, 1.5, 0.0],
            "survivors": [
                {
                    "profile": {
                        "name": "Wrong",
                        "type": "adult",
                        "priority": "low",
                    },
                    "position": [40.0, 40.0, 9.0],
                }
            ],
            "assets": [
                {
                    "asset_id": "unknown_asset",
                    "position": [1.5, 1.5, 4.0],
                    "size": [9.0, 9.0, 9.0],
                    "rotation_yaw": 15.0,
                },
                {
                    "asset_id": "standing_wall",
                    "position": [18.0, 18.0, 0.0],
                    "size": [4.0, 0.35, 2.4],
                    "rotation_yaw": 0.0,
                },
            ],
            "hazards": [
                {
                    "hazard_id": "fire-1",
                    "type": "fire",
                    "center": [1.5, 1.5, 0.0],
                    "radius": 4.0,
                    "height": 0.05,
                    "severity": "high",
                }
            ],
            "notes": "generated by fake model",
        }
    )


def test_scenario_agent_uses_antigravity_base_agent_and_gemini_prompt() -> None:
    agent = ScenarioAgent(client=object())

    assert agent.managed_agent.base_agent == SCENARIO_BASE_AGENT
    assert SCENARIO_MODEL in agent.managed_agent.system_prompt
    assert "survivor close to rubble" in agent.managed_agent.system_prompt


def test_extract_json_object_handles_markdown_fences() -> None:
    payload = extract_json_object(f"```json\n{make_scene_json()}\n```")

    assert json.loads(payload)["description"] == "earthquake collapse"


def test_generate_scene_accepts_assets_without_sizes() -> None:
    payload = json.loads(make_scene_json())
    for asset in payload["assets"]:
        asset.pop("size", None)
    fake = FakeManagedAgent(json.dumps(payload))
    scenario_agent = ScenarioAgent(managed_agent=fake)  # type: ignore[arg-type]

    scene = scenario_agent.generate_scene(
        "Collapsed apartment after earthquake.",
        survivor_count=1,
        survivor_profiles=[SurvivorProfile(name="Maya", type="baby", priority="critical")],
        difficulty="easy",
    )

    assert scene.assets[0].asset_id == "rubble_pile_small"
    assert scene.assets[0].size == ASSET_CATALOG["rubble_pile_small"].size
    assert scene.assets[1].asset_id == "standing_wall"
    assert scene.assets[1].size == ASSET_CATALOG["standing_wall"].size


def test_generate_scene_preserves_survivor_profiles_and_repairs_output() -> None:
    fake = FakeManagedAgent(make_scene_json())
    scenario_agent = ScenarioAgent(managed_agent=fake)  # type: ignore[arg-type]
    profiles = [
        SurvivorProfile(name="Maya", type="baby", priority="critical"),
        SurvivorProfile(name="Luis", type="adult", priority="medium"),
    ]

    scene = scenario_agent.generate_scene(
        "Collapsed apartment after earthquake.",
        survivor_count=2,
        survivor_profiles=profiles,
        difficulty="hard",
    )

    assert fake.last_prompt is not None
    assert scene.description == "Collapsed apartment after earthquake."
    assert scene.difficulty == "hard"
    assert [survivor.profile for survivor in scene.survivors] == profiles
    assert len(scene.survivors) == 2
    assert len(scene.assets) >= MIN_ASSETS_BY_DIFFICULTY["hard"]
    assert len(scene.hazards) >= MIN_HAZARDS_BY_DIFFICULTY["hard"]
    assert all(survivor.position[2] == 0.0 for survivor in scene.survivors)
    assert all(asset.asset_id in ASSET_CATALOG for asset in scene.assets)
    assert all(asset.position[2] == asset.size[2] / 2 for asset in scene.assets)
    assert len({asset.rotation_yaw for asset in scene.assets}) >= 4
    assert sum(asset.rotation_yaw in {0, 90, 180} for asset in scene.assets) <= 1
    survivor_rubble_distances = [
        nearest_rubble_distance(survivor.position, scene.assets)
        for survivor in scene.survivors
    ]
    assert all(distance is not None for distance in survivor_rubble_distances)
    assert all(
        distance <= MAX_SURVIVOR_RUBBLE_DISTANCE_METERS
        for distance in survivor_rubble_distances
        if distance is not None
    )
    assert all(hazard.radius <= 2.2 for hazard in scene.hazards)


def test_repair_scene_adds_missing_survivors_and_uses_catalog_sizes() -> None:
    scene = SceneSpec(
        description="bad scene",
        difficulty="easy",
        robot_start=(-10.0, -10.0, 4.0),
        survivors=[],
        assets=[
            PlacedAsset(
                asset_id="concrete_slab",
                position=(100.0, 100.0, 20.0),
                size=(9.0, 9.0, 9.0),
            )
        ],
        hazards=[
            HazardZone(
                hazard_id="gas-1",
                type="gas",
                center=(100.0, -100.0, 1.0),
                radius=99.0,
            )
        ],
    )
    profiles = [SurvivorProfile(name="Asha", type="child", priority="high")]

    repaired = repair_scene(scene, "fixed scene", "medium", 1, profiles)

    assert repaired.description == "fixed scene"
    assert repaired.difficulty == "medium"
    assert len(repaired.assets) >= MIN_ASSETS_BY_DIFFICULTY["medium"]
    assert len(repaired.hazards) >= MIN_HAZARDS_BY_DIFFICULTY["medium"]
    assert repaired.robot_start == (0.45, 0.45, 0.0)
    assert repaired.survivors[0].profile == profiles[0]
    assert repaired.assets[0].size == ASSET_CATALOG["concrete_slab"].size
    distance = nearest_rubble_distance(repaired.survivors[0].position, repaired.assets)
    assert distance is not None
    assert distance <= MAX_SURVIVOR_RUBBLE_DISTANCE_METERS
    assert repaired.hazards[0].radius == 2.2


def test_scene_spec_writes_json_and_preview_html(tmp_path: Path) -> None:
    scene = SceneSpec(
        description="Collapsed warehouse rescue",
        difficulty="medium",
        robot_start=(1.5, 1.5, 0.0),
        survivors=[
            SurvivorLocation(
                profile=SurvivorProfile(
                    name="Maya",
                    type="baby",
                    priority="critical",
                ),
                position=(18.0, 18.0, 0.0),
            )
        ],
        assets=[
            PlacedAsset(
                asset_id="rubble_pile_small",
                position=(8.0, 8.0, 0.275),
                size=ASSET_CATALOG["rubble_pile_small"].size,
            )
        ],
        hazards=[
            HazardZone(
                hazard_id="fire-1",
                type="fire",
                center=(4.0, 10.0, 0.0),
                radius=1.0,
            )
        ],
    )

    json_path = scene.save_json(tmp_path / "scene.json")
    html_path = scene.save_preview_html(tmp_path / "scene.html")

    assert json.loads(json_path.read_text(encoding="utf-8"))["description"] == (
        "Collapsed warehouse rescue"
    )
    html_text = html_path.read_text(encoding="utf-8")
    assert "ScenarioAgent Preview" in html_text
    assert "asset-top" in html_text
    assert "0.6m" in html_text
    assert "Maya" in html_text
